CREATE TABLE category
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name              VARCHAR(255),
    description       VARCHAR(255),
    created_date_time TIMESTAMP WITHOUT TIME ZONE,
    updated_date_time TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_category PRIMARY KEY (id)
);